apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: c2hvYmhpdHR5YWdpMTk5Ng==
  password: VHlhZ2lAMDAxMQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app4-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: newapp4
        image: shobhittyagi1996/mynodejs-applicationimage:latest
        ports:
        - containerPort: 8080
        env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
